swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string

  
openapi: 3.0.3
info:
  title: Bank Argent API
  description: Documentation de l'API pour la gestion des utilisateurs et des transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: http://localhost:3001/api/v1
paths:
  /transactions/current-month:
    get:
      summary: Transactions du mois en cours
      description: Récupère toutes les transactions du mois en cours, groupées par compte.
      tags:
        - Transactions
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Transactions récupérées avec succès
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/TransactionResponse'
        '401':
          description: Non autorisé
        '500':
          description: Erreur interne du serveur

  /transaction/{transactionID}:
    get:
      summary: Détails d'une transaction
      description: Récupère les détails d'une transaction spécifique à partir de son ID.
      tags:
        - Transactions
      parameters:
        - name: transactionID
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '401':
          description: Non autorisé
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur

    patch:
      summary: Modifier une transaction
      description: Permet de modifier les informations d'une transaction spécifique.
      tags:
        - Transactions
      parameters:
        - name: transactionID
          in: path
          required: true
          description: ID de la transaction
          schema:
            type: string
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: Nouvelle description de la transaction
                category:
                  type: string
                  description: Nouvelle catégorie de la transaction
                note:
                  type: string
                  description: Nouvelle note associée à la transaction
      responses:
        '200':
          description: Transaction modifiée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Données invalides
        '401':
          description: Non autorisé
        '404':
          description: Transaction introuvable
        '500':
          description: Erreur interne du serveur

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginPayload:
      type: object
      properties:
        email:
          type: string
          description: Adresse e-mail de l'utilisateur
        password:
          type: string
          description: Mot de passe de l'utilisateur
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: Jeton d'authentification JWT
    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: ID unique de l'utilisateur
        name:
          type: string
          description: Nom complet de l'utilisateur
        email:
          type: string
          description: Adresse e-mail de l'utilisateur
    TransactionResponse:
      type: object
      properties:
        transactionID:
          type: string
          description: ID de la transaction
        transactionType:
          type: string
          description: Type de la transaction (crédit ou débit)
        date:
          type: string
          format: date-time
          description: Date de la transaction
        description:
          type: string
          description: Description de la transaction
        amount:
          type: number
          format: double
          description: Montant de la transaction
        balance:
          type: number
          format: double
          description: Solde après la transaction
        category:
          type: string
          description: Catégorie de la transaction
        note:
          type: string
          description: Note associée à la transaction